[package]
name = "teensy"
version = "0.1.0"
authors = ["Nils VAN ZUIJLEN <nils.van-zuijlen@mailo.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
